version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - markie-social
    volumes:
      - ./pgdata/dev:/var/lib/postgresql/data
  # test-db:
  #   image: postgres:13
  #   ports:
  #     - 5435:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123
  #     POSTGRES_DB: nest
  #   networks:
  #     - markie-social
networks:
  markie-social:
