POST http://localhost:3002/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "amber1@gmail.com",
    "password": "123456",
    "firstName":"Markie",
    "lastName":"Tan",
    "isBlocked":true
}
###

POST http://localhost:3002/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "amber1@gmail.com",
    "password": "123456"
}