POST http://localhost:3002/auth/signup HTTP/1.1
content-type: application/json

{
    "email": "ambere@gmail.com",
    "password": "123456",
    "firstName":"Markie",
    "lastName":"Tan",
    "isBlocked":true
}
###

POST http://localhost:3002/auth/signin HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFtYmVyZUBnbWFpbC5jb20iLCJpZCI6MTgsImlhdCI6MTY3NzQ5MDgyOSwiZXhwIjoxNjc3NDkxNzI5fQ.Q8YfjfQXpOlsYwYKqVLmYWUoMwQcOpDP8SyoJqmyWIg

{
    "email": "ambere@gmail.com",
    "password": "123456"
}